name: Playwright Tests
# on:
#   push:
#     branches: [main, master]
#   pull_request:
#     branches: [main, master]
# jobs:
#   test:
#     timeout-minutes: 60
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#       - uses: actions/setup-node@v3
#         with:
#           node-version: 20
#       - name: Install dependencies
#         run: cd ./client && npm ci
#       - name: cd ./client && Install Playwright Browsers
#         run: cd ./client && npx playwright install --with-deps
#       - name: cd ./client && Run Playwright tests
#         run: cd ./client && npx playwright test
#       - uses: actions/upload-artifact@v3
#         if: always()
#         with:
#           name: playwright-report
#           path: playwright-report/
#           retention-days: 30
